### ISSUE TITLE
Update to work with latest version of Fabulous 0.41.0

### ISSUE THREAD

**Issue by sandeepc24** [Zaid-Ajaj/fabulous-simple-elements#10]
I cannot use this package with latest version of Fabulous, could this be fixed.

**Comment by Zaid-Ajaj** [comment]
That's because this library depends on [Fabulous.Core](https://www.nuget.org/packages/Fabulous.Core/) and not [Fabulous](https://www.nuget.org/packages/Fabulous/), is Fabulous.Core deprecated now?

**Comment by sandeepc24** [comment]
The new release has been restructured, and it looks like Fabulous.Core is no longer there.

I have done the changes and created a pull request.

**Comment by Zaid-Ajaj** [comment]
Fixed by #11
