### ISSUE TITLE
Using simple elements with Fabulous 0.53 fails with link error when deploying to phone (not simulator)

### ISSUE THREAD

**Issue by franko-franicevich** [Zaid-Ajaj/fabulous-simple-elements#20]
Simulator and other builds work fine when using xamarin on mac, but an actual build fails with a linking error:

```MTOUCH : error MT2101: Can't resolve the reference 'Fabulous.AttributeKey`1<Xamarin.Forms.Color> Fabulous.XamarinForms.ViewAttributes::get_ForegroundColorAttribKey()', referenced from the method 'Fabulous.ViewElement Span::span(Microsoft.FSharp.Collections.FSharpList`1<Span/ISpanProp>)' in 'Fabulous.XamarinForms, Version=0.52.0.0, Culture=neutral, PublicKeyToken=null'.```

After some digging, it turns out that in simple elements,  `span.fs`, line 47, causes a compile failure when using fab 0.53:
      ?foregroundColor = find Keys.ForegroundColor,

Digging against the fabulous.xamarinForms project itself, you can see that the foreground element was removed from span description in the core.json files that follow from 0.52 to 0.53:

https://github.com/fsprojects/Fabulous/blame/v0.52/Fabulous.XamarinForms/src/Fabulous.XamarinForms/Xamarin.Forms.Core.json
https://github.com/fsprojects/Fabulous/blame/v0.53/Fabulous.XamarinForms/src/Fabulous.XamarinForms/Xamarin.Forms.Core.json

The following appears in .52, and not in .53:
```        {

385
          "source": "ForegroundColor"
386
        },
```

Commenting out the line referencing foregroundColor in simple elements span.fs:47 results in a successful build and deploy of our project to a phone.

I'd submit a pull request, but I'm not sure if it's the *right* fix, or if the fabulous project needs to add the foreground attribute back. As far as I can tell from the docs, the foreground attribute has not been deprecated in xamarin.forms span:

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.span.foregroundcolor?view=xamarin-forms

Please let me know if you need any further information or clarification on this. For now we'll manually building the simple-elements project to work around this issue.

If you want me to submit a pull request for the probably *incorrect* fix (given foreground still seems to be in the API), please let me know. If you think I should raise this issue elsewhere, please also let me know.

**Comment by Zaid-Ajaj** [comment]
Hello @franko-franicevich, 

Thanks a lot for filing the issue and for investigating the problem :pray: 

Since the property `ForegroundColor` has been removed in 0.53.0 we have three options:
 - Upgrade this library to support latest Fabulous (what we usually do, PRs are welcome) 
 - Downgrade the Fabulous version to 0.52.0 to match the dependency of this library
 - File an issue on Fabulous to bring back `ForegroundColor` and once it is returned, we upgrade this library accordingly 

> As far as I can tell from the docs, the foreground attribute has not been deprecated in xamarin.forms span:

Indeed it looks like it is still there so I believe option 3 is the best way to go :smile:

**Comment by franko-franicevich** [comment]
Sounds good, I've created an issue against Fabulous:

https://github.com/fsprojects/Fabulous/issues/717

Couple things to think about: The reason we're upgrading to fab 0.53 is because it supports XamarinForms 4.5.

The reason we need 4.5 is because it fixes an issue with using a deprecated iOS API that may result in the apple store rejecting new app submissions at the end of this month.

So a resolution for simple-elements to make it compatible with 0.53 in the short term is probably needed. 
We're fine now with building directly, but I'm not sure if anyone else using simple-elements is in the same situation.

I'll issue a pull request for this at some point today, and leave it to you to decide :)

Thanks for your quick response on this.

**Comment by Zaid-Ajaj** [comment]
> I'll issue a pull request for this at some point today, and leave it to you to decide :)

That would be great @franko-franicevich :heart: I will publish a new version ASAP when you do so :wink:

**Comment by Zaid-Ajaj** [comment]
Fixed in #21
