### ISSUE TITLE
The module/namespace 'Fabulous' from compilation unit 'Fabulous' did not contain the val 'ValLinkagePartialKey(Create)'

### ISSUE THREAD

**Issue by marlinla** [Zaid-Ajaj/fabulous-simple-elements#26]
I used this template. Added the two buttons at the end of the view function. It will give the below error when building.

`dotnet new fabulous-xf-app -n SqueakyApp --WPF --Android=false --iOS=false`
`The module/namespace 'Fabulous' from compilation unit 'Fabulous' did not contain the val 'ValLinkagePartialKey(Create)`

https://github.com/dotnet/fsharp/issues/9370

```    let view (model: Model) dispatch =
        View.ContentPage(
          content = View.StackLayout(padding = Thickness 20.0, verticalOptions = LayoutOptions.Center,
            children = [ 
                View.Label(text = sprintf "%d" model.Count, horizontalOptions = LayoutOptions.Center, width=200.0, horizontalTextAlignment=TextAlignment.Center)
                View.Button(text = "Increment", command = (fun () -> dispatch Increment), horizontalOptions = LayoutOptions.Center)
                View.Button(text = "Decrement", command = (fun () -> dispatch Decrement), horizontalOptions = LayoutOptions.Center)
                View.Label(text = "Timer", horizontalOptions = LayoutOptions.Center)
                View.Switch(isToggled = model.TimerOn, toggled = (fun on -> dispatch (TimerToggled on.Value)), horizontalOptions = LayoutOptions.Center)
                View.Slider(minimumMaximum = (0.0, 10.0), value = double model.Step, valueChanged = (fun args -> dispatch (SetStep (int (args.NewValue + 0.5)))), horizontalOptions = LayoutOptions.FillAndExpand)
                View.Label(text = sprintf "Step size: %d" model.Step, horizontalOptions = LayoutOptions.Center) 
                View.Button(text = "Reset", horizontalOptions = LayoutOptions.Center, command = (fun () -> dispatch Reset), commandCanExecute = (model <> initModel))
                Button.button []
                View.Button()
            ]))

**Comment by marlinla** [comment]
Using this template works in the meantime:

dotnet new --install Fabulous.XamarinForms.Templates::0.57.0

**Comment by Zaid-Ajaj** [comment]
Hi there @marlinla, this package currently depends on Fabulous v0.57 and not latest Fabulous v0.61 

I would think it should still be compatible but it seems that is not the case. I will update simple elements to match the fabulous package. Thanks for filing the issue 🙏

**Comment by Zaid-Ajaj** [comment]
Published Fabulous.SimpleElements v0.61 which from now on will match latest Fabulous version to avoid these kinds of runtime errors. Please give it a try and let me know if the problem is fixed 🙏

**Comment by marlinla** [comment]
SimpleElements now works for me on the Fabulous v0.61 template. Thank you😺
